jobs:
  docker-build-only:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - checkout: {}
    - docker/build:
        debug: true
  goodbye:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - run:
        command: echo "goodbye world"
  hadolint: {}
  hello:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - run:
        command: echo "hello world"
orbs:
  docker: circleci/docker@0.5.20
version: "2.1"
workflows:
  orbs-example:
    jobs:
    - docker-build-only:
        requires:
        - hello
        - hadolint
    - goodbye:
        requires:
        - hadolint
        - docker-build-only
    - hadolint: {}
    - hello: {}
