jobs:
  docker-build-only:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - checkout: {}
    - docker/build:
        debug: true
        image: example
  goodbye:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - run:
        command: echo "goodbye the-big-tamale"
  hello:
    docker:
    - image: circleci/buildpack-deps:buster-dind
    steps:
    - run:
        command: echo "hello the-big-tamale"
orbs:
  docker: circleci/docker@0.5.20
version: "2.1"
workflows:
  the-big-tamale:
    jobs:
    - docker-build-only:
        requires:
        - hello
        - docker/hadolint
    - docker/hadolint: {}
    - goodbye:
        requires:
        - docker/hadolint
        - docker-build-only
    - hello: {}
