jobs:
  docker-build-only:
    steps:
    - checkout: {}
    - docker/build:
        debug: true
  goodbye:
    steps:
    - run:
        command: echo "goodbye the-big-tamale"
  hadolint: {}
  hello:
    steps:
    - run:
        command: echo "hello the-big-tamale"
orbs:
  docker: circleci/docker@0.5.20
version: "2.1"
workflows:
  the-big-tamale:
    jobs:
    - docker-build-only:
        requires:
        - hello
        - hadolint
    - goodbye:
        requires:
        - hadolint
        - docker-build-only
    - hadolint: {}
    - hello: {}
