jobs:
  docker-build-only:
    docker:
    - image: debian:buster
    steps:
    - checkout: {}
    - docker/build:
        debug: true
        image: example
orbs:
  docker: circleci/docker@0.5.20
version: "2.1"
workflows:
  orbs-example:
    jobs:
    - docker-build-only: {}
    - docker/hadolint: {}
