jobs:
  docker-build-only:
    steps:
    - checkout: {}
    - docker/build:
        debug: true
orbs:
  docker: circleci/docker@0.5.20
version: "2.1"
workflows:
  orbs-example:
    jobs:
    - docker-build-only: {}
